## Path to the input database files
DBpath_seq: "path/to/your/referenceDB/sequences.fasta" # reference genomic sequence in .fasta format
DBpath_tax: path/to/your/referenceDB/taxonomy.txt" # reference taxonomy of these sequences. 

## Output
tax_DB_path: "path/to/where/you/store/databases/" # path where to write the output of the database processing pipeline. 
tax_DB_name: "Name_of_your_database" # desired name of processed database (name of the directory which will contain the output)

## Amplicons extraction
extract_and_merge: True # False to skip the extraction of gerne region and merging of taxa with identical sequence on this region.
forward_primer: CCTACGGGNGGCWGCAG # the forward PCR primer used to extract the amplicon
reverse_primer: GACTACHVGGGTATCTAATCC # the reverse PCR primer used to extract the amplicon
amplicon_min_length: 300 # the min length of the amplicon
amplicon_max_length: 500 # the max length of the amplicon
excepted_errors: 4 # the accepted number of mistmach per primer
amplicon_min_coverage: 0.9 # the proportion of the primers that must be found in the reference sequences. 

## Taxa collapsing
numbers_species: 4 # the max number of species names to be pasted together. Over this number, taxonomic names will be replaced by a space holder. 
numbers_genus: 2 # the max number of genus names to be pasted together. Over this number, taxonomic names will be replaced by a space holder.

