################ Validation config ################

### Input table, listing the taxonomy and number of assemblies to test from
input_table_path: 'ressources/template_files/insilico_ITS_input_taxID.tsv'

### In silico PCR parameters, used by Simulate_PCR
forward_primer: CYHRGYYATTTAGAGGWMSTAA # ITS1fw ambiguous
reverse_primer: RCKDYSTTCWTCRWYGHTGB # ITS2rv ambiguous

### Amplicon triming parameters, used by cutadapt
excepted_errors: 0.1 ## Proportion of mismatch tolerated allowed in the primers to be trimmed
amplicon_min_coverage: 0.8 ## Covered proporition of the primer to be trimmed
merged_min_length: 50 # 
merged_max_length: 900 #

### Database used for taxonomic assignment
tax_DB_path: "databases/unite_qiime_ver10/"
tax_DB_name: [unite_qiime_ver10_dynamic] # must be the name of the folder containing files named "DB_amp.fasta" and "DB_amp_taxonomy.txt" in /data/. Can be multiple.
classifier: ["RDP"]

### Processing for comparison of taxonomic assignment
viz_replace_empty_tax: TRUE

########### Assembly finder config ################
NCBI_key: '6dce38824889f62e188a25ae35c52a083c08'
NCBI_email: 'valentin.scherz@chuv.ch'

##Parameters for search_assemblies function
#This set of parameters is to search all possible assemblies
complete_assemblies: True ## Keep only complete assemblies
reference_assemblies: False ## Keep only reference assemblies
representative_assemblies: False ## Keep only representative assemblies
exclude_from_metagenomes: False ## Excluse from metagenome
Genbank_assemblies: False ## Take from Genbank
Refseq_assemblies: False ## Take from Refseq


##Parameters for the filtering function
Rank_to_filter_by: 'None'
#None: Assemblies are ranked by their assembly status (complete or not)
#and Refseq category (reference, representative ...)
#If you want to filter by species, set this parameter to 'species'. The filtering function will list all unique species
#and rank their assemblies according to assembly status and Refseq category.
nb_genomes: 1
# Number of assemblies to retrieve per taxID/species if several available.
