args:
  ampcov:
  classifier:
  conda_prefix:
  configfile: 
  fasta: 
  fw_primer: 
  errors:
  maxlen: 
  minlen: 
  name: 
  output: 
  processing: 
  rdp_mem: 
  rv_primer: 
  singularity_prefix:
  snake_args: 
  system_config: 
  taxonomy: 
  threads: 
  use_conda: 
  use_singularity: 