# Title     : TODO
# Objective : TODO
# Created by: valentinscherz
# Created on: 25.10.18

## Import from Marta pipeline to phyloseq

# Load objects into R
# Here, we load:
# - taxonomy table
# - Metadata table
# - features (either sequences variants or OTU) counts table
# - taxonomic tree
#
# Regarding the "taxonomy table":
#  The loaded table should have NO headers and in column 1. the features ID and in column 2. seven taxonomic ranks sepatrated by ";". We have here the option to replace or not the NA by the previous taxonomic rank and a spaceholder such as "_sp" for unassigned species
#
# Regarding the "Metadata table", it should follow the template described in doc (to be written), including beeing in the .tsv format


## Load needed libraries
library(ggplot2)
library(vegan)
library(dplyr)
library(scales)
library(grid)
library(reshape2)
library(phyloseq)
library(RColorBrewer)
library(randomcoloR)
library(tidyverse)
library(biom)
library(data.table)
library(forcats)
library(ggpubr)
library(psadd)
library(taxa)
library(metacoder)
library(rlang)
library(DESeq2)
library(gtools)
library(grid)
library(decontam)



load_objects_fct <- function(taxonomy_class_table, replace_empty_tax = TRUE, features_counts_table , Metadata_table) {

### Transform the OTU table to be imported in phyloseq

### Read the otu_table generated by Marta's pipeline
marta_otus_tax_table <- read.table(file = paste0(features_counts_table), header = T, sep = "\t")

### Transform this table to have a wide format where we have a column by sample
transf_marta_table <- marta_otus_tax_table %>%
  group_by(Sample, OTU_ID) %>%
  summarise(counts = sum(counts)) %>%
  dcast(OTU_ID ~ Sample)

### Set OTU as rownames
transf_marta_table <- set_rownames(x = transf_marta_table, value = transf_marta_table$OTU_ID)

### Remove the now column with OTU names
transf_marta_table$OTU_ID <- NULL

### Tranform the dataframe into a matrix
transf_marta_table_m <<- as.matrix(transf_marta_table)


### Load Metadata table into R environment
Metadata<-read_tsv(file.path(Metadata_table), col_names = TRUE)

### Save this table in global environnement
Metadata <<- Metadata


## taxonomy table

### Load into R a table with all Features ID and their taxonomic assignemnt.
taxonomy_class_table<-read_tsv(paste0(taxonomy_class_table), col_names = FALSE)

### Convert the table into a tabular split version
taxonomy_class_table<-taxonomy_class_table %>% as.tibble() %>% separate(X2, sep=";", c("Kingdom","Phylum","Class","Order","Family","Genus","Species"))

### Replace the not properly named headers into proper ones
colnames(taxonomy_class_table)[colnames(taxonomy_class_table)=="X1"] <- "Feature.ID"
colnames(taxonomy_class_table)[colnames(taxonomy_class_table)=="X3"] <- "Confidence"


### Convert taxonomic levels as character (needed for the next steps)
taxonomy_class_table$Kingdom<-as.character(taxonomy_class_table$Kingdom)
taxonomy_class_table$Phylum<-as.character(taxonomy_class_table$Phylum)
taxonomy_class_table$Class<-as.character(taxonomy_class_table$Class)
taxonomy_class_table$Order<-as.character(taxonomy_class_table$Order)
taxonomy_class_table$Family<-as.character(taxonomy_class_table$Family)
taxonomy_class_table$Genus<-as.character(taxonomy_class_table$Genus)
taxonomy_class_table$Species<-as.character(taxonomy_class_table$Species)

if(replace_empty_tax == TRUE) {
  ### Replace NA by the previous order + a space_holder for each taxonomic level
  taxonomy_class_table$Kingdom[is.na(taxonomy_class_table$Kingdom)] <- (("Unkown_Kingdom")[is.na(taxonomy_class_table$Kingdom)])
  taxonomy_class_table$Phylum[is.na(taxonomy_class_table$Phylum)] <- ((paste(taxonomy_class_table$Kingdom,"_phy",sep=""))[is.na(taxonomy_class_table$Phylum)])
  taxonomy_class_table$Class[is.na(taxonomy_class_table$Class)] <- ((paste(taxonomy_class_table$Phylum,"_clas",sep=""))[is.na(taxonomy_class_table$Class)])
  taxonomy_class_table$Order[is.na(taxonomy_class_table$Order)] <- ((paste(taxonomy_class_table$Class,"_ord",sep=""))[is.na(taxonomy_class_table$Order)])
  taxonomy_class_table$Family[is.na(taxonomy_class_table$Family)] <- ((paste(taxonomy_class_table$Order,"_fam",sep=""))[is.na(taxonomy_class_table$Family)])
  taxonomy_class_table$Genus[is.na(taxonomy_class_table$Genus)] <- ((paste(taxonomy_class_table$Family,"_gen",sep=""))[is.na(taxonomy_class_table$Genus)])
  taxonomy_class_table$Species[is.na(taxonomy_class_table$Species)] <- ((paste(taxonomy_class_table$Genus,"_sp",sep=""))[is.na(taxonomy_class_table$Species)])

  print("table NA remplaced by spaceholders")

}else{

  print("table NA NOT remplaced by spaceholders")
}

### Convert taxonomic levels back as factor (Not sure if really needed?)
taxonomy_class_table$Kingdom<-as.factor(taxonomy_class_table$Kingdom)
taxonomy_class_table$Phylum<-as.factor(taxonomy_class_table$Phylum)
taxonomy_class_table$Class<-as.factor(taxonomy_class_table$Class)
taxonomy_class_table$Order<-as.factor(taxonomy_class_table$Order)
taxonomy_class_table$Family<-as.factor(taxonomy_class_table$Family)
taxonomy_class_table$Genus<-as.factor(taxonomy_class_table$Genus)
taxonomy_class_table$Species<-as.factor(taxonomy_class_table$Species)

### Save this table in global environnement
taxonomy_class_table <<- taxonomy_class_table


}
