# Title     : TODO
# Objective : TODO
# Created by: valentinscherz
# Created on: 29.10.18

## Inspired from https://gist.github.com/erictleung/eda33bceceebb190eb9a44c93a077d32
## Redirect R output
log <- file(snakemake@log[[1]], open="wt")
sink(log)
sink(log, type="message")

## Load needed library
library(dplyr);packageVersion("dplyr")
library(reshape2);packageVersion("reshape2")

## Input
features_counts_table <- snakemake@input[["OTU_count_table"]]

## Output
count_table <- snakemake@output[["Qiim"]]


### Transform the OTU table to be imported in phyloseq

### Read the otu_table generated by Marta's pipeline
marta_otus_tax_table <- read.table(file = features_counts_table, header = T, sep = "\t")

### Transform this table to have a wide format where we have a column by sample
transf_marta_table <- marta_otus_tax_table %>%
  group_by(Sample, OTU_ID) %>%
  summarise(counts = sum(counts)) %>%
  dcast(OTU_ID ~ Sample)

### Set OTU as rownames
transf_marta_table <- set_rownames(x = transf_marta_table, value = transf_marta_table$OTU_ID)

### Remove the now column with OTU names
transf_marta_table$OTU_ID <- NULL

